parameters:
#    am_presence.example.class: Am\PresenceBundle\Example

services:
#    am_presence.example:
#        class: %am_presence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
