parameters:
    am.work.class: Am\PresenceBundle\Entity\Work
    am.workManager.class: Am\PresenceBundle\Entity\WorkManager

services:
    am.work.manager:
        class: %am.workManager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - %am.work.class%